site:
  title: Lisk Docs Demo Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: http://104.248.38.54
  start_page: lisk-sdk::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    toc: ~
    imagesdir: ~
  extensions:
#  - asciidoctor-emoji
  - asciidoctor-plantuml
#  - asciidoctor-chart
  - ./lib/tabs-block/extension.js
content:
  sources:
          #- url: https://github.com/tschakki/lisk-docs.git
          #branches: [development, asciidoc-tschakki]
    #branches: [development, dev-start, master]
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [docs-sdk, docs-core, docs-protocol-1.0, docs-protocol-1.1, docs-core-2.0.0, docs-core-1.6.0, docs-sdk-2.0.0, docs-sdk-2.1.0, docs-sdk-2.2.0]
    #start_path: docs
ui:
  bundle:
    url: https://github.com/Tschakki/antora-ui-lisk/raw/tabs-test/build/ui-bundle.zip
    snapshot: true

